export const pointDefinitions = {
  frontal: [
    { id: 'eu_L', name: 'eu_L - Латерально выступающая точка на боковой поверхности головы слева' },
    { id: 'eu_R', name: 'eu_R - Латерально выступающая точка на боковой поверхности головы справа' },
    { id: 'zy_L', name: 'zy_L - Наиболее выступающая кнаружи точка скуловой дуги слева' },
    { id: 'zy_R', name: 'zy_R - Наиболее выступающая кнаружи точка скуловой дуги справа' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' },
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'gn', name: 'gn - Gnatios (наиболее выступающая точка подбородка)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'oph', name: 'oph - Оphrion (точка на пересечении средней линии лица и касательной к надбровным дугам)' }
  ],
  frontalSmile: [
    { id: 'eu_L', name: 'eu_L - Латерально выступающая точка на боковой поверхности головы слева' },
    { id: 'eu_R', name: 'eu_R - Латерально выступающая точка на боковой поверхности головы справа' },
    { id: 'zy_L', name: 'zy_L - Наиболее выступающая кнаружи точка скуловой дуги слева' },
    { id: 'zy_R', name: 'zy_R - Наиболее выступающая кнаружи точка скуловой дуги справа' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' },
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'gn', name: 'gn - Gnatios (наиболее выступающая точка подбородка)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'oph', name: 'oph - Оphrion (точка на пересечении средней линии лица и касательной к надбровным дугам)' },
    { id: 'ch_L', name: 'ch_L - Commissura labiorum (угол рта слева)' },
    { id: 'ch_R', name: 'ch_R - Commissura labiorum (угол рта справа)' }
  ],
  frontalRetractorsClosed: [
    { id: 'eu_L', name: 'eu_L - Латерально выступающая точка на боковой поверхности головы слева' },
    { id: 'eu_R', name: 'eu_R - Латерально выступающая точка на боковой поверхности головы справа' },
    { id: 'zy_L', name: 'zy_L - Наиболее выступающая кнаружи точка скуловой дуги слева' },
    { id: 'zy_R', name: 'zy_R - Наиболее выступающая кнаружи точка скуловой дуги справа' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' },
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'gn', name: 'gn - Gnatios (наиболее выступающая точка подбородка)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'oph', name: 'oph - Оphrion (точка на пересечении средней линии лица и касательной к надбровным дугам)' },
    { id: 'u1_tip', name: 'u1_tip - Верхушка центрального резца' },
    { id: 'l1_tip', name: 'l1_tip - Верхушка нижнего центрального резца' }
  ],
  frontalRetractorsOpen: [
    { id: 'eu_L', name: 'eu_L - Латерально выступающая точка на боковой поверхности головы слева' },
    { id: 'eu_R', name: 'eu_R - Латерально выступающая точка на боковой поверхности головы справа' },
    { id: 'zy_L', name: 'zy_L - Наиболее выступающая кнаружи точка скуловой дуги слева' },
    { id: 'zy_R', name: 'zy_R - Наиболее выступающая кнаружи точка скуловой дуги справа' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' },
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'gn', name: 'gn - Gnatios (наиболее выступающая точка подбородка)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'oph', name: 'oph - Оphrion (точка на пересечении средней линии лица и касательной к надбровным дугам)' },
    { id: 'u1_tip', name: 'u1_tip - Верхушка центрального резца' },
    { id: 'l1_tip', name: 'l1_tip - Верхушка нижнего центрального резца' },
    { id: 'u6_mesiobuccal', name: 'u6_mesiobuccal - Медиально-щечная точка верхнего первого моляра' },
    { id: 'l6_mesiobuccal', name: 'l6_mesiobuccal - Медиально-щечная точка нижнего первого моляра' }
  ],
  profileRight: [
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'pro', name: 'pro - Pronasale (кончик носа)' },
    { id: 'pog', name: 'pog - Pogonion (наиболее выступающая точка подбородка)' },
    { id: 'ls', name: 'ls - Labrale superius (наиболее выступающая точка верхней губы)' },
    { id: 'coll', name: 'coll - Точка для проведения касательной к нижнему краю носа' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' },
    { id: 'me', name: 'me - Menton (нижняя точка подбородка)' }
  ],
  profileLeft: [
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'pro', name: 'pro - Pronasale (кончик носа)' },
    { id: 'pog', name: 'pog - Pogonion (наиболее выступающая точка подбородка)' },
    { id: 'ls', name: 'ls - Labrale superius (наиболее выступающая точка верхней губы)' },
    { id: 'coll', name: 'coll - Точка для проведения касательной к нижнему краю носа' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' },
    { id: 'me', name: 'me - Menton (нижняя точка подбородка)' }
  ],
  profileSmileRight: [
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'pro', name: 'pro - Pronasale (кончик носа)' },
    { id: 'pog', name: 'pog - Pogonion (наиболее выступающая точка подбородка)' },
    { id: 'ls', name: 'ls - Labrale superius (наиболее выступающая точка верхней губы)' },
    { id: 'coll', name: 'coll - Точка для проведения касательной к нижнему краю носа' },
    { id: 'ch_R', name: 'ch_R - Commissura labiorum (угол рта справа)' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' }
  ],
  profileSmileLeft: [
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'pro', name: 'pro - Pronasale (кончик носа)' },
    { id: 'pog', name: 'pog - Pogonion (наиболее выступающая точка подбородка)' },
    { id: 'ls', name: 'ls - Labrale superius (наиболее выступающая точка верхней губы)' },
    { id: 'coll', name: 'coll - Точка для проведения касательной к нижнему краю носа' },
    { id: 'ch_L', name: 'ch_L - Commissura labiorum (угол рта слева)' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' }
  ],
  profile45Right: [
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'zy_R', name: 'zy_R - Наиболее выступающая кнаружи точка скуловой дуги справа' },
    { id: 'go_R', name: 'go_R - Точка угла нижней челюсти справа' },
    { id: 'pro', name: 'pro - Pronasale (кончик носа)' },
    { id: 'ls', name: 'ls - Labrale superius (наиболее выступающая точка верхней губы)' }
  ],
  profile45Left: [
    { id: 'n', name: 'n - Nasion (наиболее глубокая точка между носом и лбом)' },
    { id: 'sn', name: 'sn - Subnasale (середина перехода перегородки носа к верхней губе)' },
    { id: 'pg', name: 'pg - Pogonion (наиболее выступающая точка подбородочного выступа)' },
    { id: 'zy_L', name: 'zy_L - Наиболее выступающая кнаружи точка скуловой дуги слева' },
    { id: 'go_L', name: 'go_L - Точка угла нижней челюсти слева' },
    { id: 'pro', name: 'pro - Pronasale (кончик носа)' },
    { id: 'ls', name: 'ls - Labrale superius (наиболее выступающая точка верхней губы)' }
  ],
  intraoralFrontalClosed: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u1_R', name: 'u1_R - Центральный резец справа' },
    { id: 'u1_L', name: 'u1_L - Центральный резец слева' },
    { id: 'u2_R', name: 'u2_R - Боковой резец справа' },
    { id: 'u2_L', name: 'u2_L - Боковой резец слева' }
  ],
  intraoralFrontalOpen: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u1_R', name: 'u1_R - Центральный резец справа' },
    { id: 'u1_L', name: 'u1_L - Центральный резец слева' },
    { id: 'u2_R', name: 'u2_R - Боковой резец справа' },
    { id: 'u2_L', name: 'u2_L - Боковой резец слева' },
    { id: 'l1_R', name: 'l1_R - Нижний центральный резец справа' },
    { id: 'l1_L', name: 'l1_L - Нижний центральный резец слева' },
    { id: 'l2_R', name: 'l2_R - Нижний боковой резец справа' },
    { id: 'l2_L', name: 'l2_L - Нижний боковой резец слева' }
  ],
  intraoralRight90: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u6_mesiobuccal', name: 'u6_mesiobuccal - Медиально-щечная точка верхнего первого моляра' },
    { id: 'u7_mesiobuccal', name: 'u7_mesiobuccal - Медиально-щечная точка верхнего второго моляра' },
    { id: 'l6_mesiobuccal', name: 'l6_mesiobuccal - Медиально-щечная точка нижнего первого моляра' },
    { id: 'l7_mesiobuccal', name: 'l7_mesiobuccal - Медиально-щечная точка нижнего второго моляра' }
  ],
  intraoralRight45: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u5_distobuccal', name: 'u5_distobuccal - Дистально-щечная точка верхнего первого премоляра' },
    { id: 'u6_mesiobuccal', name: 'u6_mesiobuccal - Медиально-щечная точка верхнего первого моляра' },
    { id: 'l5_distobuccal', name: 'l5_distobuccal - Дистально-щечная точка нижнего первого премоляра' },
    { id: 'l6_mesiobuccal', name: 'l6_mesiobuccal - Медиально-щечная точка нижнего первого моляра' }
  ],
  intraoralLeft90: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u6_mesiobuccal', name: 'u6_mesiobuccal - Медиально-щечная точка верхнего первого моляра слева' },
    { id: 'u7_mesiobuccal', name: 'u7_mesiobuccal - Медиально-щечная точка верхнего второго моляра слева' },
    { id: 'l6_mesiobuccal', name: 'l6_mesiobuccal - Медиально-щечная точка нижнего первого моляра слева' },
    { id: 'l7_mesiobuccal', name: 'l7_mesiobuccal - Медиально-щечная точка нижнего второго моляра слева' }
  ],
  intraoralLeft45: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u5_distobuccal', name: 'u5_distobuccal - Дистально-щечная точка верхнего первого премоляра слева' },
    { id: 'u6_mesiobuccal', name: 'u6_mesiobuccal - Медиально-щечная точка верхнего первого моляра слева' },
    { id: 'l5_distobuccal', name: 'l5_distobuccal - Дистально-щечная точка нижнего первого премоляра слева' },
    { id: 'l6_mesiobuccal', name: 'l6_mesiobuccal - Медиально-щечная точка нижнего первого моляра слева' }
  ],
  intraoralUpper: [
    { id: 'midline_upper', name: 'midline_upper - Средняя линия верхней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'u1_R', name: 'u1_R - Центральный резец справа' },
    { id: 'u1_L', name: 'u1_L - Центральный резец слева' },
    { id: 'u6_mesiobuccal', name: 'u6_mesiobuccal - Медиально-щечная точка верхнего первого моляра справа' },
    { id: 'u6_mesiobuccal_L', name: 'u6_mesiobuccal_L - Медиально-щечная точка верхнего первого моляра слева' }
  ],
  intraoralLower: [
    { id: 'midline_lower', name: 'midline_lower - Средняя линия нижней челюсти' },
    { id: 'canine_R', name: 'canine_R - Клык справа' },
    { id: 'canine_L', name: 'canine_L - Клык слева' },
    { id: 'l1_R', name: 'l1_R - Нижний центральный резец справа' },
    { id: 'l1_L', name: 'l1_L - Нижний центральный резец слева' },
    { id: 'l6_mesiobuccal', name: 'l6_mesiobuccal - Медиально-щечная точка нижнего первого моляра справа' },
    { id: 'l6_mesiobuccal_L', name: 'l6_mesiobuccal_L - Медиально-щечная точка нижнего первого моляра слева' }
  ]
};
